package com.cave;

public enum Action {
    ABSTAIN,TAKE,DROP,OPEN,CLOSE,ON,OFF,WAVE,CALM,GO,RELAX,
    POUR,EAT,DRINK,RUB,TOSS,WAKE,FEED,FILL,BREAK,BLAST,KILL,
    SAY,READ,FEEFIE,BRIEF,FIND,INVENTORY,SCORE,QUIT
}
