package com.cave;

public enum Motion {
    N, S, E, W, NE,SE,NW,SW,U,D,L,R,IN,OUT,FORWARD,BACK,
    OVER,ACROSS,UPSTREAM,DOWNSTREAM,
    ENTER,CRAWL,JUMP,CLIMB,LOOK,CROSS,
    ROAD,WOODS,VALLEY,HOUSE,GULLY,STREAM,DEPRESSION,ENTRANCE,CAVE,
    ROCK,SLAB,BED,PASSAGE,CAVERN,CANYON,AWKWARD,SECRET,BEDQUILT,RESERVOIR,
    GIANT,ORIENTAL,SHELL,BARREN,BROKEN,DEBRIS,VIEW,FORK,
    PIT,SLIT,CRACK,DOME,HOLE,WALL,HALL,ROOM,FLOOR,
    STAIRS,STEPS,COBBLES,SURFACE,DARK,LOW,OUTDOORS,
    Y2,XYZZY,PLUGH,PLOVER,OFFICE,NOWHERE;
}
